services:
  fastapi-agent:
    image: zzang6535/gamyeon-agent:latest
    restart: always
    container_name: fastapi-app
    networks:
      - gamyeon-net
      ports:
      - "8000:8000"
    environment:
      - CONSUL_HOST=consul

networks:
  gamyeon-net:
    external: true  # 외부 네트워크 연결