services:
  agent-server:
    image: zzang6535/gamyeon-agent:latest
    restart: always
    container_name: AGENT_SERVER
    ports:
      - "8000:8000"
    environment:
      - CONSUL_HOST=consul
    networks:
      - gamyeon-net

networks:
  gamyeon-net:
    external: true
